run:
	@go run ./cmd/main.go

docker-build:
	@docker build -t {{.Name}}-image .

docker-run:
	@docker run --env-file ./.env --name {{.Name}}-container {{.Name}}-image

# Manage RabbitMQ container
rabbitmq-up:
	@docker-compose up -d

rabbitmq-down:
	@docker-compose down

rabbitmq-down-rm-vol:
	@docker-compose down -v