run:
	@go run ./cmd/main.go

docker-build:
	@docker build -t {{.Name}}-image .

docker-run:
	@docker run --env-file ./.env --name {{.Name}}-container {{.Name}}-image

# Manage Redis container
redis-up:
	@docker-compose up -d

redis-down:
	@docker-compose down

redis-down-rm-vol:
	@docker-compose down -v